# CENTRA Configuration
BASE_URL = ""
UPLOAD_URL = ""
CENTRA_USERNAME = ""
CENTRA_PASSWORD = ""

# Device Configuration
DEVICE_ID = ""
DEVICE_SERIAL = ""

#Template Configuration
IS_SCENARIO = False
CREATE_TEMPLATE = False
EDIT_TEMPLATE = False
TEMPLATE_NAME = ""
FILE_PREFIX = ""
SAME_AS_TEST_NAME = False
DETACH_ATTACH = True